INSERT INTO subject (subject_name,
                     professor_name,
                     completion,
                     subject_code,
                     department,
                     time,
                     credit)
VALUES ('프로그래밍2및실습',
        '교수님1',
        '전공필수',
        1001,
        '글로벌미디어학부',
        3,
        3),
       ('미디어제작및실습',
        '교수님2',
        '전공필수',
        1002,
        '글로벌미디어학부',
        3,
        3),
       ('컴퓨터시스템개론',
        '교수님3',
        '전공필수',
        1003,
        '글로벌미디어학부',
        3,
        3);
