SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `comment`;
TRUNCATE TABLE `evaluation`;
TRUNCATE TABLE `posts`;
TRUNCATE TABLE `star`;
TRUNCATE TABLE `student_subject`;
TRUNCATE TABLE `student`;
TRUNCATE TABLE `subject`;

SET FOREIGN_KEY_CHECKS = 1;