@serverUrl = localhost:8080

@subjectId = 1
@postsId = 1

@email = "nggus5@soongsil.ac.kr"
@password = "leopassword123123"

// 숭실숨고 로그인 요청
###
POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

> {%
    const responseBody = response.body;
    client.log("accessToken: " + responseBody.accessToken);
%}
###

// 게시글 작성
###
POST {{serverUrl}}/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "subjectId" : {{subjectId}},
  "title" : "title",
  "content" : "content"
}
###

//게시글 조회
###
GET {{serverUrl}}/posts/{{postsId}}

###

//과목별 게시글 조회
###
GET {{serverUrl}}/posts/subjects/{{subjectId}}?page=1&size=10&sortBy=earliest
###