@serverUrl = localhost:8080

@subjectId = 1
@postsId = 1

// 질문 등록
###
POST {{serverUrl}}/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "subjectId" : {{subjectId}},
  "title" : "title",
  "content" : "content"
}
###

// 과목별 질문 조회
###
GET {{serverUrl}}/posts/subjects/{{subjectId}}?page=1&size=10&sortBy=earliest
Content-Type: application/json

###

// 나의 질문 조회
###
GET {{serverUrl}}/students/posts?page=1&size=10&sortBy=earliest
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

// 질문 상세 조회
###
GET {{serverUrl}}/posts/{{postsId}}
Content-Type: application/json

###
