@serverUrl = localhost:8080

@accessToken = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..9NaKe3XXktKBxPfi.c0vCaoNyffN6fLUFmlqCM_IEWSKdBzUrAmBdHM32DsyjpzFmuD0Uf4UFScw.rVTXxdOS7A4DNO0nmpYJpg

@subjectId = 1

@postsId = 1

// 게시글 작성
###
POST {{serverUrl}}/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "subjectId" : {{subjectId}},
  "title" : "title",
  "content" : "content"
}
###

//게시글 조회
###
GET {{serverUrl}}/posts/{{postsId}}

###

//과목별 게시글 조회
###
GET {{serverUrl}}/posts/subjects/{{subjectId}}?page=1&size=10&sortBy=earliest
###