@serverUrl = localhost:8080

@email = "nggus5@soongsil.ac.kr"
@password = "leopassword123123"

// 숭실숨고 로그인 요청
###
POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

> {%
    const responseBody = response.body;
    client.log("accessToken: " + responseBody.accessToken);
%}
###

// 유저 정보 조회
###
GET {{serverUrl}}/students
Authorization: Bearer {{accessToken}}

###