@serverUrl = localhost:8080

@subjectId = 1
@subjectCode = 2

@email = "nggus5@soongsil.ac.kr"
@password = "leopassword123123"

// 숭실숨고 로그인 요청
###
POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}

> {%
    const responseBody = response.body;
    client.global.set("accessToken", responseBody.result.accessToken);
%}

###

// 과목 등록
###
POST {{serverUrl}}/subjects
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "subjectName": "subjectName",
  "professorName": "professorName",
  "completion": "completion",
  "subjectCode": {{subjectCode}},
  "department": "department",
  "time": 1,
  "credit": 1
}

###

// 수강 과목 등록
###
POST {{serverUrl}}/subjects/students
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "subjectId": {{subjectId}},
  "years": 2024,
  "semester": 1
}

###

//전체 과목 조회
###
GET {{serverUrl}}/subjects
Content-Type: application/json

###

//수강 중인 과목 조회
###
GET {{serverUrl}}/subjects/students
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###