name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Build with Gradle(with Test)
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew clean build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.YOURSSU_SECRET}}
          HOST: ${{ secrets.TEST_HOST }}
          USER: ${{ secrets.TEST_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/*.jar $USER@$HOST:/ssumgo/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST 'sudo kill -9 $(lsof -t -i:8085) && DB_HOST=${DB_HOST} DB_USERNAME=${DB_USERNAME} DB_PASSWORD=${DB_PASSWORD} sudo nohup java -jar /ssumgo/ssumgo-0.0.1-SNAPSHOT.jar &'
