name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.YOURSSU_SECRET}}
          HOST: ${{ secrets.TEST_HOST }}
          USER: ${{ secrets.TEST_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/*.jar $USER@$HOST:/ssumgo/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST '/ssumgo/run.sh'